### ISSUE TITLE
Snazzy Shelter appears to be broken

### ISSUE THREAD

**Issue by RoseIlanga** [yellowsink/shelter-plugins#9] opened 2023-11-11 09:37 UTC
Hey, wasn't sure what to title it, but Snazzy Shelter's entire functionality appears to be broken, I'm guessing since the big Discord update. I can't enable and disable themes, search through the store (except for the search bar and the "show all" dropdown, everything is blank), add repos (can remove them though), or use the quick CSS (completely blank).

Let me know if there's any other information I can provide, like console logs or screenshots.

**Comment by RoseIlanga** [comment] 2023-11-11 16:47
Here. I've tried to get as much console output as possible to make it easier to figure out the problem.

When clicking the button to disable a theme:
```
(index):4 Uncaught (in promise) TypeError: Failed to fetch
    at He ((index):4:185)
    at Ge ((index):4:376)
    at ls ((index):4:1424)
    at Y ((index):4:1739)
    at Proxy.map (<anonymous>)
    at bundle.js:4:53398
    at J (bundle.js:1:13698)
    at se (bundle.js:1:9409)
    at Proxy.<anonymous> (bundle.js:4:53372)
    at fd ((index):14:8189)
onChange @ (index):4
(anonymous) @ bundle.js:4
```
Trying to enable a theme:
```
TypeError: Failed to fetch
    at He ((index):4:185)
    at Ge ((index):4:376)
    at cs ((index):4:873)
    at G ((index):4:1162)
    at Object.onChange ((index):4:8238)
    at HTMLInputElement.<anonymous> (bundle.js:4:21700) TypeError: Failed to fetch
    at He ((index):4:185)
    at ss ((index):4:526)
    at G ((index):4:1196)
    at async Object.onChange ((index):4:8232)
G @ (index):4
await in G (async)
onChange @ (index):4
(anonymous) @ bundle.js:4
```
```
Uncaught (in promise) Error: Failed to fetch theme - both CC and BD either failed to fetch or failed to parse
    at G ((index):4:1238)
    at async Object.onChange ((index):4:8232)
G @ (index):4
await in G (async)
(anonymous) @ bundle.js:4
```
And trying to disable the theme again produced different output:
```
TypeError: Failed to fetch
    at He ((index):4:185)
    at Ge ((index):4:376)
    at cs ((index):4:873)
    at G ((index):4:1162)
    at eval ((index):4:3189)
    at Array.forEach (<anonymous>)
    at Gr ((index):4:3178)
    at eval ((index):15:3655)
    at eval ((index):15:3715)
    at ht (bundle.js:14:6274) TypeError: Failed to fetch
    at He ((index):4:185)
    at ss ((index):4:526)
    at G ((index):4:1196)
G @ (index):4
await in G (async)
onChange @ (index):4
(anonymous) @ bundle.js:4
```
```
Uncaught (in promise) Error: Failed to fetch theme - both CC and BD either failed to fetch or failed to parse
    at G ((index):4:1238)
    at async Object.onChange ((index):4:8232)
G @ (index):4
await in G (async)
(anonymous) @ bundle.js:4
```

---

Switching to the "Store" tab:
```
Refused to connect to 'https://cumcordthemes.github.io/Cumsock/repo.json' because it violates the document's Content Security Policy.
He @ (index):4
Ge @ (index):4
ls @ (index):4
Y @ (index):4
(anonymous) @ bundle.js:4
J @ bundle.js:1
se @ bundle.js:1
(anonymous) @ bundle.js:4
fd @ (index):14
ud @ (index):14
(anonymous) @ bundle.js:1
j @ bundle.js:1
Nn @ bundle.js:1
(anonymous) @ bundle.js:1
_o @ bundle.js:1
Ce @ bundle.js:1
Gn @ bundle.js:1
xo @ bundle.js:1
Ma @ (index):14
(anonymous) @ bundle.js:4
j @ bundle.js:1
(anonymous) @ bundle.js:4
_o @ bundle.js:1
Ce @ bundle.js:1
vt @ bundle.js:1
ko @ bundle.js:1
Bs @ bundle.js:1
J @ bundle.js:1
$o @ bundle.js:1
r @ bundle.js:1
c.$$click @ (index):14
gr @ bundle.js:4
```
```
POST https://o64374.ingest.sentry.io/api/5441894/security/?sentry_key=8fbbce30bf5244ec9429546beef21870 429
He @ (index):4
Ge @ (index):4
ls @ (index):4
Y @ (index):4
(anonymous) @ bundle.js:4
J @ bundle.js:1
se @ bundle.js:1
(anonymous) @ bundle.js:4
fd @ (index):14
ud @ (index):14
(anonymous) @ bundle.js:1
j @ bundle.js:1
Nn @ bundle.js:1
(anonymous) @ bundle.js:1
_o @ bundle.js:1
Ce @ bundle.js:1
Gn @ bundle.js:1
xo @ bundle.js:1
Ma @ (index):14
(anonymous) @ bundle.js:4
j @ bundle.js:1
(anonymous) @ bundle.js:4
_o @ bundle.js:1
Ce @ bundle.js:1
vt @ bundle.js:1
ko @ bundle.js:1
Bs @ bundle.js:1
J @ bundle.js:1
$o @ bundle.js:1
r @ bundle.js:1
c.$$click @ (index):14
gr @ bundle.js:4
```
```
Uncaught (in promise) TypeError: Failed to fetch
    at He ((index):4:185)
    at Ge ((index):4:376)
    at ls ((index):4:1424)
    at Y ((index):4:1739)
    at Proxy.map (<anonymous>)
    at bundle.js:4:53398
    at J (bundle.js:1:13698)
    at se (bundle.js:1:9409)
    at Proxy.<anonymous> (bundle.js:4:53372)
    at fd ((index):14:8189)
He @ (index):4
Ge @ (index):4
ls @ (index):4
Y @ (index):4
(anonymous) @ bundle.js:4
J @ bundle.js:1
se @ bundle.js:1
(anonymous) @ bundle.js:4
fd @ (index):14
ud @ (index):14
(anonymous) @ bundle.js:1
j @ bundle.js:1
Nn @ bundle.js:1
(anonymous) @ bundle.js:1
_o @ bundle.js:1
Ce @ bundle.js:1
Gn @ bundle.js:1
xo @ bundle.js:1
Ma @ (index):14
(anonymous) @ bundle.js:4
j @ bundle.js:1
(anonymous) @ bundle.js:4
_o @ bundle.js:1
Ce @ bundle.js:1
vt @ bundle.js:1
ko @ bundle.js:1
Bs @ bundle.js:1
J @ bundle.js:1
$o @ bundle.js:1
r @ bundle.js:1
c.$$click @ (index):14
gr @ bundle.js:4
Promise.then (async)
Nn @ bundle.js:1
(anonymous) @ bundle.js:1
_o @ bundle.js:1
Ce @ bundle.js:1
Gn @ bundle.js:1
xo @ bundle.js:1
Ma @ (index):14
(anonymous) @ bundle.js:4
j @ bundle.js:1
(anonymous) @ bundle.js:4
_o @ bundle.js:1
Ce @ bundle.js:1
vt @ bundle.js:1
ko @ bundle.js:1
Bs @ bundle.js:1
J @ bundle.js:1
$o @ bundle.js:1
r @ bundle.js:1
c.$$click @ (index):14
gr @ bundle.js:4
```

For brevity, it seems like some of the console errors (like the first one I posted) are almost exactly the same, so I'll omit the rest that are like that. Trying to add a theme repo has that error too every time the "Add" button is clicked.

Also had this when initially trying to add the repo:
```
(index):4 Refused to connect to 'https://yellowsink.github.io/bdthemesmirror/repo.json' because it violates the document's Content Security Policy.
He @ (index):4
Ge @ (index):4
ls @ (index):4
Y @ (index):4
Vp @ (index):14
ba @ (index):14
onClick @ (index):14
gr @ bundle.js:4
```
When switching to "Quick CSS":
```
Refused to load the script 'https://cdn.jsdelivr.net/npm/monaco-editor@0.33.0/min/vs/loader.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline' 'nonce-NzcsOTAsMjI2LDc1LDE5MywxNzksMTIsMjM4' blob: https://cdn.discordapp.com/animations/ https://www.gstatic.com/recaptcha/ https://www.google.com/recaptcha/ https://recaptcha.net/recaptcha/ https://*.hcaptcha.com https://hcaptcha.com https://js.stripe.com https://js.braintreegateway.com https://assets.braintreegateway.com https://www.paypalobjects.com https://checkout.paypal.com https://c.paypal.com https://kit.cash.app". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

xp @ (index):14
eval @ (index):14
eval @ (index):14
vp @ (index):14
ta @ (index):14
n @ (index):14
(anonymous) @ bundle.js:4
j @ bundle.js:1
T @ bundle.js:4
eval @ (index):14
ia @ (index):14
(anonymous) @ bundle.js:1
j @ bundle.js:1
f @ bundle.js:1
eval @ (index):14
da @ (index):14
(anonymous) @ bundle.js:4
j @ bundle.js:1
(anonymous) @ bundle.js:4
_o @ bundle.js:1
Ce @ bundle.js:1
vt @ bundle.js:1
ko @ bundle.js:1
Bs @ bundle.js:1
J @ bundle.js:1
$o @ bundle.js:1
r @ bundle.js:1
c.$$click @ (index):14
gr @ bundle.js:4
```
```
@me:1 Uncaught (in promise) Event {isTrusted: true, type: 'error', target: script, currentTarget: null, eventPhase: 0, …}
Promise.then (async)
eval @ (index):14
_p @ (index):14
vp @ (index):14
ta @ (index):14
n @ (index):14
(anonymous) @ bundle.js:4
j @ bundle.js:1
T @ bundle.js:4
eval @ (index):14
ia @ (index):14
(anonymous) @ bundle.js:1
j @ bundle.js:1
f @ bundle.js:1
eval @ (index):14
da @ (index):14
(anonymous) @ bundle.js:4
j @ bundle.js:1
(anonymous) @ bundle.js:4
_o @ bundle.js:1
Ce @ bundle.js:1
vt @ bundle.js:1
ko @ bundle.js:1
Bs @ bundle.js:1
J @ bundle.js:1
$o @ bundle.js:1
r @ bundle.js:1
c.$$click @ (index):14
gr @ bundle.js:4
```
```
(index):14 Uncaught (in promise) Event {isTrusted: true, type: 'error', target: script, currentTarget: null, eventPhase: 0, …}
n @ (index):14
await in n (async)
(anonymous) @ bundle.js:4
j @ bundle.js:1
T @ bundle.js:4
eval @ (index):14
ia @ (index):14
(anonymous) @ bundle.js:1
j @ bundle.js:1
f @ bundle.js:1
eval @ (index):14
da @ (index):14
(anonymous) @ bundle.js:4
j @ bundle.js:1
(anonymous) @ bundle.js:4
_o @ bundle.js:1
Ce @ bundle.js:1
vt @ bundle.js:1
ko @ bundle.js:1
Bs @ bundle.js:1
J @ bundle.js:1
$o @ bundle.js:1
r @ bundle.js:1
c.$$click @ (index):14
gr @ bundle.js:4
```

Hope this helps!

**Comment by yellowsink** [comment] 2023-11-12 21:22
This looks like a csp issue. Which platform (desktop, Firefox, chrome) are you running? I'm surprised that plugins load.

Sent from Outlook for Android

EDIT: sorry for the delayed reply, I genuinely replied to this yesterday but it just sat in my drafts folder :skull:

**Comment by RoseIlanga** [comment] 2023-11-13 06:01
No problem, it happens :P I'm running Shelter via Armcord (so technically it counts as a "web" client) on Manjaro. Could it be an issue with Armcord, then? Though it was fine until a few weeks ago as I recall.

**Comment by yellowsink** [comment] 2023-11-13 11:12
Hmm. I'll test when I next have free time.

**Comment by DeadLyBro** [comment] 2024-01-03 14:38
(I don't know what is Snazzy Shelter but...) 
If it's still not resolved and if you want to import css, if you have, paste this into Css Editor and edit;
```css
@import url("https://cdn.jsdelivr.net/gh/author-username/repo-name@latest/sub_folder?/file.ext");
```
Note: You can change `@latest` to `@version` like `@0123456789`, if you want old build. 

I tried to import css from Github and I got error, so I tried like that and it worked. 
I hope it's useful for who search for this.

**Comment by yellowsink** [comment] 2024-01-03 15:19
Cannot repro, using armcord as you are, just all works exactly as intended for me.

if this is still an issue then ill look into it more but im tempted to close this because it all just seems to be entirely fine to me

See this demo: https://cdn.hyrule.pics/3cea875ad.mp4

**Closed as not planned by yellowsink** 2024-01-03 15:19 UTC
